amccaugh/phidl

- phidl/geometry.py
Fixed bugs in test_comb where structure would form poorly if wire width was large. Also fixed starting point of zig-zag overlay and length of comb wires. 
Note: in test_comb, the parameter wire_gap is the distance between zig zag wires. If the wire_gap and wire_width are equal, the comb wires will touch the zig zag wires.
Added parameter in test_ic for pad_gap (which is the separation between the top and bottom pad).
> Test structures Bug Fixes

- phidl/device_layout.py
Most rotations are multiples of 90 degrees.
Before going into trigonometry, the rotate function checks this. If it is a multiple, then rotation is just a change of dimensions. It results in significant speedups, about 60% time for a typical real layout (tested on the WG-NW wafer).
> Faster rotating

- setup.py
numpy 1.16.0 was released two days ago. It renamed a function called `_validate_lengths` which scikit-image expects.
This patch makes it so fresh installs or --upgrades of phidl will downgrade your numpy to the latest working version.
The scikit people are working on it:
https://github.com/scikit-image/scikit-image/issues/3649
> Explicit require numpy 1.15.4

- phidl/device_layout.py
Before, it was also removing all `DeviceReferences`.
> remove_layers no longer removes DeviceReferences

- CHANGELOG.md
- README.md
- phidl/device_layout.py
- setup.py
Bugfix release
- Fix for Device xmin/xmax/ymin/ymax property assignment (e.g. `D.xmin = 30`) causing incorrect movement of references and labels
> PHIDL 1.4.2

- phidl/path.py
Hey,
This pull request fixes a bug that required the points that are passed in to path.smooth to start with a horizontal segment that moves to the right.
When starting with a horizontal segment, `path.smooth` correctly passes via each waypoint:
```py3
points = np.array([[0, 0], [1, 0], [1, 1], [0, 1]])
path = pp.smooth(points, radius=0.1)
qp(path)
fig = plt.figure('PHIDL quickplot')
ax = fig.axes[0]
ax.scatter(points[:,0], points[:,1])
```
To trigger the bug, one can use a path that does not begin with a horizontal segment
```py3
points = np.array([[0, 0], [-1, 0], [-1, 1], [0, 1]])
path = pp.smooth(points, radius=0.1)
qp(path)
fig = plt.figure('PHIDL quickplot')
ax = fig.axes[0]
ax.scatter(points[:,0], points[:,1])
ax.set_xlim((-1.2, 1.2))
ax.set_ylim((-1.2, 1.2))
```
To fix, we apply a …
> Allow path.smooth to start with non-horizontal path

- docs/outline_open_ports.ipynb
- phidl/geometry.py
Added the keyword argument `open_ports=-1`. The default value (-1) returns a completely outlined object. Setting `open_ports` to a positive `int` or `float` will trim (boolean 'A-B') the outline at the element's ports with a rectangle of `size=(distance, port.width + open_ports*distance)`. For right angle geometry set `open_ports=0` to trim just the width of the port or set `open_ports=2` to trim completely through the outline. For non right angle geometry a factor greater than 2 might be necessary to trim the entire geometry.
> Update outline with open_ports

- phidl/path.py
Hi, 
First, thanks for all your work on this repository! It's been very nice to work with and makes layouts much easier.
I found that path.smooth will make funny curlicue turns in some cases. For example, when the path goes from pointing south to pointing west, the path will circle left 270 degrees instead of just turning 90 degrees right.  Here's a snippet to reproduce the problem:
```
import numpy as np
from matplotlib import pyplot as plt
from phidl import quickplot as qp
import phidl.path as pp
points = np.array([(0, -10), (0, 0), (-10, 0), (-10, -10), (-20, -10), (-20, 0)])
path = pp.smooth(points, radius=1)
qp(path)
plt.show()
```
The curlicue turns are caused by the turn angle calculation, which can produce turn angles in the range [-360, 360]. Wrapping the turn angle into the …
> Fix curlicue turns in path.smooth

- phidl/path.py
Hi Adam,
The new path module is great ^^
It you transition Cross-sections where one of the cross-section does not have any named sections you get an empty Device
with this fix, it will raise an error instead of returning an empty Device
```
from phidl import CrossSection, Device
import phidl.path as pp
from phidl import quickplot as qp
X1 = CrossSection()
X1.add(width=1.2, offset=0, layer=2, ports=("in1", "out1"))
X1.add(width=2.2, offset=0, layer=3)
X1.add(width=1.1, offset=3, layer=1)
X2 = CrossSection()
X2.add(width=1, offset=0, layer=2, name="wg", ports=("in2", "out2"))
X2.add(width=3.5, offset=0, layer=3, name="etch")
X2.add(width=3, offset=5, layer=1, name="wg2")
P1 = pp.straight(length=5)
P2 = pp.straight(length=5)
WG1 = P1.extrude(cross_section=X1)
WG2 = …
```
> raise error if empty_transition

- phidl/device_layout.py
Hi Adam,
at the moment when absorbing a reference the labels disappear
this PR makes that when you absorb a reference the labels are copied too so they don't get removed
> fix absorb

- phidl/geometry.py
Boolean operation within geometry.outline() should be "B-A" for distance < 0.
> Fix a bug in geometry.outline() for distance < 0

- phidl/device_layout.py
When importing a GDS the layer number is a np.int64 instead of int.
Therefore `_parse_layer` isn't working correctly. This fixes it.
> Check whether a numbers.Number is used to make work with np.int64

- phidl/device_layout.py
- phidl/geometry.py
- tests/test_device.py
Preserve Polygon.properties and DeviceReference.properties when saving and loading.
See
```python 
import os
import tempfile
fname = os.path.join(tempfile.mkdtemp(), 'properties.gds')
d = phidl.geometry.bbox()
d.polygons[0].properties[1] = 'yolo'
r = d << phidl.geometry.bbox()
r.properties[1] = "foo"
d.write_gds(fname)
d2 = phidl.geometry.import_gds(fname)
assert d2.polygons[0].properties == d.polygons[0].properties
assert d2.references[0].properties == r.properties
```
> Preserve Polygon.properties and DeviceReference.properties when saving and loading

- phidl/geometry.py
Suggestion to make boolean `'or'` merge all shapes within one Device, even if the second Device is `None` (or other way around).
Similar behavior to a `gdspy.boolean(multi_path, None, "or", max_points=0)` where 'multi_path' is a `gdspy.Path` with multiple elements.
For the trivial solutions to remain complete, a new `elif` case needs to be added for `(len(A_polys) == 0) and (len(B_polys) == 0) and (operation == 'or')` as `operation == 'or'` was moved out of the first case.
> Fix a bug in boolean 'or' to always merge polys

- .github/workflows/pytest.yml
- .pre-commit-config.yaml
- phidl/geometry.py
See release notes:
https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations
> Ragged array creation will now always raise a `ValueError` unless `dtype=object` is passed. This includes very deeply nested sequences.
> ([gh-22004](https://github.com/numpy/numpy/pull/22004))
Currently, with numpy 1.24.1 I am getting:
```
2023-01-05T19:03:38.4295117Z     p = pg._boolean_polygons_parallel(
2023-01-05T19:03:38.4295422Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2023-01-05T19:03:38.4295597Z 
2023-01-05T19:03:38.4295891Z polygons_A = [array([[  96.493244, -119.142818],
2023-01-05T19:03:38.4296237Z        [  96.493244, -110.586912],
2023-01-05T19:03:38.4296536Z        [  93.473899, -107.567567],
2023-01-05T19:03:38.4296781Z        [ …
```
> Make object arrays to prevent ValueError in numpy 1.24

- phidl/geometry.py
numpy has only a np.object_ type.
In the function the dtype is missing a underline after np.object_ (https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.object_)
> Small Typo in the geometry.grid function, np.object instead of np.object_Np.object typo

- phidl/geometry.py
- tests/test_geometry.py
fix grid to allow for empty shape parameter to recover old functionality that was removed in 5d91d44f1920dd64a9497a7ec34a851410696c0c.
> pg.grid: move shape parameter reordering to allow for empty shape

- phidl/device_layout.py
I noticed this was the slowest part in my code when profiling on large pcells. This change vectorizes the function.
Right now, this function doesn't even show up in the top 100 slowest lines.
> Speedup _reflect_points (160x in simple test)

- phidl/geometry.py
- tests/test_geometry.py
This pull request addresses an issue where property keys are incorrectly interpreted as signed integers when importing GDS files using the `import_gds` function in `phidl.geometry`. The issue is caused by a bug in the `gdspy` library (heitzmann/gdspy#240).
When saving properties using `gdspy`, the keys are directly written to the GDS file as unsigned 16-bit integers (2 bytes). However, when loading the GDS file, `gdspy` interprets the keys as signed integers, resulting in negative values for keys greater than 32767.
This leads to incorrect property keys in the loaded GDS elements when using `phidl.geometry.import_gds`.
To work around this issue, a new function `_correct_properties` has been added to `phidl.geometry`. This function corrects the properties dictionary of a loaded GDS element …
> Fix incorrect property keys when importing GDS files

- .github/workflows/pytest.yml
- README.md
- phidl/device_layout.py
- phidl/geometry.py
- phidl/path.py
- requirements.txt
- ruff.toml
- setup.py
- tests/test_geometry.py
NumPy 2.0 is set to be released on June 16. I've been adding support in a couple other projects so figured I'd try to help out here if you're interested.
The process here was mainly to run the [ruff plugin](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin) and fix what it caught. I used `np.float64` where I needed to pick a float precision, because that seemed more common in your code.
I also added the optional dependencies I found when running tests as extras, so you can install them with `pip install phidl[all]` (or `[test]`). Then I updated a few places that were causing `DeprecationWarning`s.
> Numpy 2.0 support
